import type { Metadata } from "next";
import "./globals.css";
import { Oxanium, Geist } from "next/font/google";
import { cn } from "@/lib/utils";

const geistHeading = Geist({subsets:['latin'],variable:'--font-heading'});

const oxanium = Oxanium({subsets:['latin'],variable:'--font-sans'});


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full antialiased", "font-sans", oxanium.variable, geistHeading.variable)}
    >
      <body className="min-h-full flex flex-col">

        {/* navbar */}

        {children}
        
        {/* footer */}
      
        </body>
    </html>
  );
}
